/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Gyanendra
 */
public class Edit_Course extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Course
     */
    DefaultTableModel model;
    public Edit_Course() {
        initComponents();
         setRecordsTable();
    }
    public void setRecordsTable(){
        try{
           Connection con=DBConnection.getConnection();
              PreparedStatement pst=con.prepareStatement("select * from course");
              ResultSet rs = pst.executeQuery(); 
              while(rs.next()){
                   String courseId=rs.getString("course_Id");
                  String courseName=rs.getString("Course_Name");
                  String cost=rs.getString("cost");
                 
                  
                  Object[] obj ={courseId,courseName,cost};
                  
                  model=(DefaultTableModel)tbl_courseData.getModel();
                  model.addRow(obj);
                  
              }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void addCourse(int id,String cname,double cost)
    {
        try{
          Connection con=DBConnection.getConnection();
              PreparedStatement pst=con.prepareStatement("insert into course values(?,?,?)");
              pst.setInt(1, id);
              pst.setString(2,cname);
              pst.setDouble(3, cost);
              int rowCount=pst.executeUpdate();
              if(rowCount==1){
                  JOptionPane.showMessageDialog(this,"course added successfully");
                  clearTable();
                  setRecordsTable();
              }
              else{
                 JOptionPane.showMessageDialog(this,"course insertion failed");  
              }
              
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,"course insertion failed");
           e.printStackTrace();
        }
    }
    public void update(int id,String cname,double cost){
        try{
          Connection con=DBConnection.getConnection();
              PreparedStatement pst=con.prepareStatement("update course set course_name=?,cost=? where course_id=?");
             
              pst.setString(1,cname);
              pst.setDouble(2,cost);
               pst.setInt(3,id);
              int rowCount=pst.executeUpdate();
              if(rowCount==1){
                  JOptionPane.showMessageDialog(this,"course updated successfully");
                  clearTable();
                  setRecordsTable();
              }
              else{
                 JOptionPane.showMessageDialog(this,"course updation failed");  
              }
              
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,"course updation failed");
           e.printStackTrace();
        }  
    }
    public void delete(int id){
        try{
          Connection con=DBConnection.getConnection();
              PreparedStatement pst=con.prepareStatement("delete from course where course_id=?");
               pst.setInt(1,id);
              int rowCount=pst.executeUpdate();
              if(rowCount==1){
                  JOptionPane.showMessageDialog(this,"course deleted successfully");
                  clearTable();
                  setRecordsTable();
              }
              else{
                 JOptionPane.showMessageDialog(this,"course deletion failed");  
              }
              
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,"course deletion failed");
           e.printStackTrace();
        }  
    }
    public void clearTable(){
        DefaultTableModel model=(DefaultTableModel)tbl_courseData.getModel();
        model.setRowCount(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_sidebar = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        panel_search_record = new javax.swing.JPanel();
        btn_search_record = new javax.swing.JLabel();
        panel_edit_course = new javax.swing.JPanel();
        btn_edit_course = new javax.swing.JLabel();
        panel_course_list = new javax.swing.JPanel();
        btn_course_list = new javax.swing.JLabel();
        panel_all_record = new javax.swing.JPanel();
        btn_all_record = new javax.swing.JLabel();
        panel_back = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        panel_logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_courseData = new javax.swing.JTable();
        txt_courseId = new javax.swing.JTextField();
        txt_coursePrice = new javax.swing.JTextField();
        txt_courseName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(0, 102, 102));
        panel_sidebar.setForeground(new java.awt.Color(255, 255, 255));
        panel_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_home.setBackground(new java.awt.Color(0, 102, 102));
        panel_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_home.setForeground(new java.awt.Color(255, 255, 255));
        panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        lbl_home.setText("  Home");
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homeMouseExited(evt);
            }
        });
        panel_home.add(lbl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        panel_sidebar.add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 200, 60));

        panel_search_record.setBackground(new java.awt.Color(0, 102, 102));
        panel_search_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_search_record.setForeground(new java.awt.Color(255, 255, 255));
        panel_search_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search_record.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btn_search_record.setText("Search Record");
        btn_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseExited(evt);
            }
        });
        panel_search_record.add(btn_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 60));

        panel_sidebar.add(panel_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, 60));

        panel_edit_course.setBackground(new java.awt.Color(0, 102, 102));
        panel_edit_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_edit_course.setForeground(new java.awt.Color(255, 255, 255));
        panel_edit_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_edit_course.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_edit_course.setText("Edit Courses");
        btn_edit_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseExited(evt);
            }
        });
        panel_edit_course.add(btn_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 60));

        panel_sidebar.add(panel_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 60));

        panel_course_list.setBackground(new java.awt.Color(0, 102, 102));
        panel_course_list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_course_list.setForeground(new java.awt.Color(255, 255, 255));
        panel_course_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_course_list.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_course_list.setForeground(new java.awt.Color(255, 255, 255));
        btn_course_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1.png"))); // NOI18N
        btn_course_list.setText("Course List");
        btn_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_course_listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_course_listMouseExited(evt);
            }
        });
        panel_course_list.add(btn_course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 60));

        panel_sidebar.add(panel_course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 60));

        panel_all_record.setBackground(new java.awt.Color(0, 102, 102));
        panel_all_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_all_record.setForeground(new java.awt.Color(255, 255, 255));
        panel_all_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_all_record.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_all_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_all_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_all_record.setText("View All Record");
        btn_all_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseExited(evt);
            }
        });
        panel_all_record.add(btn_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        panel_sidebar.add(panel_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 200, 60));

        panel_back.setBackground(new java.awt.Color(0, 102, 102));
        panel_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_back.setForeground(new java.awt.Color(255, 255, 255));
        panel_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btn_back.setText("   Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        panel_back.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        panel_sidebar.add(panel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 200, 60));

        panel_logout.setBackground(new java.awt.Color(0, 102, 102));
        panel_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_logout.setForeground(new java.awt.Color(255, 255, 255));
        panel_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        panel_logout.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        panel_sidebar.add(panel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 200, 60));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 942, -1));

        getContentPane().add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 310, 760));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_courseData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Course Price"
            }
        ));
        tbl_courseData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_courseDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_courseData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 530, 480));

        txt_courseId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_courseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, 30));

        txt_coursePrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_coursePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coursePriceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_coursePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 190, 30));

        txt_courseName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Course Price :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Course Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Course Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 429, 90, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 429, 90, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        home1 home=new home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseEntered
        Color clr=new Color(0,153,153);
        panel_home.setBackground(clr);
    }//GEN-LAST:event_lbl_homeMouseEntered

    private void lbl_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseExited
        Color clr=new Color(0,102,102);
        panel_home.setBackground(clr);
    }//GEN-LAST:event_lbl_homeMouseExited

    private void btn_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseClicked
        Search_Rocord search=new Search_Rocord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_search_recordMouseClicked

    private void btn_search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseEntered
        Color clr=new Color(0,153,153);
        panel_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseEntered

    private void btn_search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseExited
        Color clr=new Color(0,102,102);
        panel_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseExited

    private void btn_edit_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseEntered
        Color clr=new Color(0,153,153);
        panel_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseEntered

    private void btn_edit_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseExited
        Color clr=new Color(0,102,102);
        panel_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseExited

    private void btn_course_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseEntered
        Color clr=new Color(0,153,153);
        panel_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseEntered

    private void btn_course_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseExited
        Color clr=new Color(0,102,102);
        panel_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseExited

    private void btn_all_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseEntered
        Color clr=new Color(0,153,153);
        panel_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_all_recordMouseEntered

    private void btn_all_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseExited
        Color clr=new Color(0,102,102);
        panel_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_all_recordMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        Color clr=new Color(0,153,153);
        panel_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        Color clr=new Color(0,102,102);
        panel_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        Color clr=new Color(0,153,153);
        panel_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        Color clr=new Color(0,102,102);
        panel_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void txt_coursePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coursePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coursePriceActionPerformed

    private void tbl_courseDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_courseDataMouseClicked
        int rowNo=tbl_courseData.getSelectedRow();
        TableModel model=tbl_courseData.getModel();
        
        txt_courseId.setText(model.getValueAt(rowNo, 0).toString());
          txt_courseName.setText(model.getValueAt(rowNo, 2).toString());
            txt_coursePrice.setText(model.getValueAt(rowNo, 1).toString());
        
    }//GEN-LAST:event_tbl_courseDataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int id=Integer.parseInt(txt_courseId.getText());
       String cname=txt_courseName.getText();
       double cost=Double.parseDouble(txt_coursePrice.getText());
       
       addCourse(id,cname,cost);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int id=Integer.parseInt(txt_courseId.getText());
       String cname=txt_courseName.getText();
       double cost=Double.parseDouble(txt_coursePrice.getText());
       
        update(id,cname,cost);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id=Integer.parseInt(txt_courseId.getText());
       delete(id);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_edit_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseClicked
        Edit_Course edit=new Edit_Course();
       edit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_edit_courseMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
    home1 home=new home1();
        home.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_all_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseClicked
          View_All_Record record=new View_All_Record();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_all_recordMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Logout Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_all_record;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_course_list;
    private javax.swing.JLabel btn_edit_course;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_search_record;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JPanel panel_all_record;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_course_list;
    private javax.swing.JPanel panel_edit_course;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel panel_search_record;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JTable tbl_courseData;
    private javax.swing.JTextField txt_courseId;
    private javax.swing.JTextField txt_courseName;
    private javax.swing.JTextField txt_coursePrice;
    // End of variables declaration//GEN-END:variables
}
