/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Gyanendra
 */
public class home1 extends javax.swing.JFrame {

    /**
     * Creates new form home1
     */
    public home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_searchRecord = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_addFees = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_editCourse = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_viewCourse = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_viewReport = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_viewRecord = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_about = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        try {
            jPanel2 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "fees_management_system.home1_jPanel2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_searchRecord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_searchRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search-document.png"))); // NOI18N
        lbl_searchRecord.setText("Search Record");
        lbl_searchRecord.setIconTextGap(1);
        lbl_searchRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_searchRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_searchRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_searchRecordMouseExited(evt);
            }
        });
        jPanel4.add(lbl_searchRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 140));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 260, 140));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_addFees.setBackground(new java.awt.Color(102, 102, 102));
        lbl_addFees.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_addFees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/plus.png"))); // NOI18N
        lbl_addFees.setText("Add Fees");
        lbl_addFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addFeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addFeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addFeesMouseExited(evt);
            }
        });
        jPanel3.add(lbl_addFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 140));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_editCourse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_editCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        lbl_editCourse.setText("Edit Course");
        lbl_editCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_editCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_editCourseMouseExited(evt);
            }
        });
        jPanel6.add(lbl_editCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 140));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, 140));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewCourse.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_viewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_viewCourse.setText("View Course");
        lbl_viewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewCourseMouseExited(evt);
            }
        });
        jPanel7.add(lbl_viewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 140));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 260, 140));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewReport.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_viewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view report.png"))); // NOI18N
        lbl_viewReport.setText("View Report");
        lbl_viewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewReportMouseExited(evt);
            }
        });
        jPanel8.add(lbl_viewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 140));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 270, 140));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewRecord.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_viewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_viewRecord.setText("View Record");
        lbl_viewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseExited(evt);
            }
        });
        jPanel5.add(lbl_viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 130));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 280, 140));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        lbl_logout.setText("Log Out");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseExited(evt);
            }
        });
        jPanel9.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 170, -1));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_about.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/about.png"))); // NOI18N
        lbl_about.setText("About");
        lbl_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseExited(evt);
            }
        });
        jPanel10.add(lbl_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 70));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background images/home background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 530));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setText("RBMI");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, 40));

        jLabel10.setBackground(new java.awt.Color(0, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 204));
        jLabel10.setText("Rakshpal Bahadur Management Institute Bareilly");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 610, 30));

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));
        jLabel11.setText("Faridpur Road Near ITBP Bhukara");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 390, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_addFeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addFeesMouseEntered
        Color clr=new Color(0,51,51);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_lbl_addFeesMouseEntered

    private void lbl_addFeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addFeesMouseExited
         Color clr=new Color(102,102,102);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_lbl_addFeesMouseExited

    private void lbl_searchRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_searchRecordMouseEntered
        Color clr=new Color(0,51,51);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_lbl_searchRecordMouseEntered

    private void lbl_searchRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_searchRecordMouseExited
        Color clr=new Color(102,102,102);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_lbl_searchRecordMouseExited

    private void lbl_viewRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseEntered
          Color clr=new Color(0,51,51);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_lbl_viewRecordMouseEntered

    private void lbl_viewRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseExited
         Color clr=new Color(102,102,102);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_lbl_viewRecordMouseExited

    private void lbl_editCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editCourseMouseEntered
        Color clr=new Color(0,51,51);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_lbl_editCourseMouseEntered

    private void lbl_editCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editCourseMouseExited
         Color clr=new Color(102,102,102);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_lbl_editCourseMouseExited

    private void lbl_viewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewCourseMouseEntered
         Color clr=new Color(0,51,51);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_lbl_viewCourseMouseEntered

    private void lbl_viewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewCourseMouseExited
          Color clr=new Color(102,102,102);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_lbl_viewCourseMouseExited

    private void lbl_viewReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReportMouseEntered
         Color clr=new Color(0,51,51);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_lbl_viewReportMouseEntered

    private void lbl_viewReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReportMouseExited
        Color clr=new Color(102,102,102);
        jPanel8.setBackground(clr); 
    }//GEN-LAST:event_lbl_viewReportMouseExited

    private void lbl_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseEntered
         Color clr=new Color(0,51,51);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_lbl_logoutMouseEntered

    private void lbl_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseExited
       Color clr=new Color(102,102,102);
        jPanel9.setBackground(clr); 
    }//GEN-LAST:event_lbl_logoutMouseExited

    private void lbl_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseEntered
         Color clr=new Color(0,51,51);
        jPanel10.setBackground(clr);
    }//GEN-LAST:event_lbl_aboutMouseEntered

    private void lbl_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseExited
         Color clr=new Color(102,102,102);
        jPanel10.setBackground(clr); 
    }//GEN-LAST:event_lbl_aboutMouseExited

    private void lbl_addFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addFeesMouseClicked
        add_fees addfees=new add_fees();
        addfees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addFeesMouseClicked

    private void lbl_searchRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_searchRecordMouseClicked
        Search_Rocord search=new Search_Rocord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_searchRecordMouseClicked

    private void lbl_editCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editCourseMouseClicked
       Edit_Course edit=new Edit_Course();
       edit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbl_editCourseMouseClicked

    private void lbl_viewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReportMouseClicked
       Report_Generate r=new Report_Generate();
       r.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbl_viewReportMouseClicked

    private void lbl_viewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseClicked
        View_All_Record record=new View_All_Record();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewRecordMouseClicked

    private void lbl_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseClicked
       About about=new About();
       about.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbl_aboutMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Logout Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_addFees;
    private javax.swing.JLabel lbl_editCourse;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_searchRecord;
    private javax.swing.JLabel lbl_viewCourse;
    private javax.swing.JLabel lbl_viewRecord;
    private javax.swing.JLabel lbl_viewReport;
    // End of variables declaration//GEN-END:variables
}
