/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Gyanendra
 */
public class Print_receipt extends javax.swing.JFrame {

    /**
     * Creates new form Print_receipt
     */
    public Print_receipt() {
        initComponents();
        getRecords();
    }
    public void getRecords(){
        try{
         Connection con=DBConnection.getConnection();
              PreparedStatement pst=con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
              ResultSet rs = pst.executeQuery();
              rs.next();
              lbl_recipetNo.setText(rs.getString("reciept_no"));
              lbl_paymentMode.setText(rs.getString("payment_mode"));
              String paymentMode=rs.getString("payment_mode");
              if(paymentMode.equalsIgnoreCase("cash"))
              {
            lbl_cheque_dd.setText("");
            txt_cheque_dd.setText("cheque_no");
            txt_bankName.setText("");
             }
              if(paymentMode.equalsIgnoreCase("cheque"))
              {
           lbl_cheque_dd.setText("cheque_no");
            txt_cheque_dd.setText(rs.getString("cheque_no"));
           txt_bankName.setText(rs.getString("bank_name"));
             }
                if(paymentMode.equalsIgnoreCase("dd"))
              {
           lbl_cheque_dd.setText("dd_no");
            txt_cheque_dd.setText(rs.getString("cheque_no"));
            txt_bankName.setText(rs.getString("bank_name"));
             }
                  if(paymentMode.equalsIgnoreCase("card"))
              {
           lbl_cheque_dd.setText("cheque_no");
            txt_cheque_dd.setText(rs.getString(""));
            txt_bankName.setText(rs.getString("bank_name"));
             }
                 lbl_recivedForm.setText(rs.getString("student_name"));
                 lbl_date.setText(rs.getString("date"));
                 lbl_gstIN.setText(rs.getString("gstin"));
                 lbl_year1.setText(rs.getString("year1"));
                 lbl_year2.setText(rs.getString("year2"));
                 lbl_rollNo.setText(rs.getString("roll_no"));
                 
                 lbl_initialAmount.setText(rs.getString("amount"));
                 lbl_cgst.setText(rs.getString("cgst"));
                 lbl_sgst.setText(rs.getString("sgst"));
                 lbl_totalAmount.setText(rs.getString("total_amount"));
                 lbl_totalInWords.setText(rs.getString("total_in_words"));
                 lbl_remark.setText(rs.getString("remark"));
                 lbl_course.setText(rs.getString("course_name"));
                  
              
        }
        catch(Exception e){
          e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_sidebar = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        panel_search_record = new javax.swing.JPanel();
        btn_search_record = new javax.swing.JLabel();
        panel_edit_course = new javax.swing.JPanel();
        btn_edit_course = new javax.swing.JLabel();
        panel_course_list = new javax.swing.JPanel();
        btn_course_list = new javax.swing.JLabel();
        panel_all_record = new javax.swing.JPanel();
        btn_all_record = new javax.swing.JLabel();
        panel_back = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_logout = new javax.swing.JPanel();
        panel_logout3 = new javax.swing.JPanel();
        btn_logout2 = new javax.swing.JLabel();
        panel_logout = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        panel_logout1 = new javax.swing.JPanel();
        btn_logout1 = new javax.swing.JLabel();
        panel_edit = new javax.swing.JLabel();
        btn_print = new javax.swing.JPanel();
        panel_logout5 = new javax.swing.JPanel();
        btn_logout4 = new javax.swing.JLabel();
        panel_print = new javax.swing.JLabel();
        panel_parent = new javax.swing.JPanel();
        lbl_recipetNo = new javax.swing.JLabel();
        lbl_paymentMode = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_gstIN = new javax.swing.JLabel();
        panel_child = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_totalInWords = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_remark = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        lbl_cgst = new javax.swing.JLabel();
        lbl_sgst = new javax.swing.JLabel();
        lbl_totalAmount = new javax.swing.JLabel();
        lbl_head = new javax.swing.JLabel();
        lbl_initialAmount = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_srNo1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_head2 = new javax.swing.JLabel();
        lbl_head3 = new javax.swing.JLabel();
        lbl_year1 = new javax.swing.JLabel();
        txt_button = new javax.swing.JButton();
        lbl_rollNo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_recivedForm = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        lbl_year2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_gst_no1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_sidebar.setBackground(new java.awt.Color(0, 102, 102));
        panel_sidebar.setForeground(new java.awt.Color(255, 255, 255));
        panel_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_home.setBackground(new java.awt.Color(0, 102, 102));
        panel_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_home.setForeground(new java.awt.Color(255, 255, 255));
        panel_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        lbl_home.setText("  Home");
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homeMouseExited(evt);
            }
        });
        panel_home.add(lbl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 60));

        panel_sidebar.add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 60));

        panel_search_record.setBackground(new java.awt.Color(0, 102, 102));
        panel_search_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_search_record.setForeground(new java.awt.Color(255, 255, 255));
        panel_search_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search_record.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btn_search_record.setText("Search Record");
        btn_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseExited(evt);
            }
        });
        panel_search_record.add(btn_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 60));

        panel_sidebar.add(panel_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 60));

        panel_edit_course.setBackground(new java.awt.Color(0, 102, 102));
        panel_edit_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_edit_course.setForeground(new java.awt.Color(255, 255, 255));
        panel_edit_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_edit_course.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_edit_course.setText("Edit Courses");
        btn_edit_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseExited(evt);
            }
        });
        panel_edit_course.add(btn_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 60));

        panel_sidebar.add(panel_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 60));

        panel_course_list.setBackground(new java.awt.Color(0, 102, 102));
        panel_course_list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_course_list.setForeground(new java.awt.Color(255, 255, 255));
        panel_course_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_course_list.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_course_list.setForeground(new java.awt.Color(255, 255, 255));
        btn_course_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1.png"))); // NOI18N
        btn_course_list.setText("Course List");
        btn_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_course_listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_course_listMouseExited(evt);
            }
        });
        panel_course_list.add(btn_course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 60));

        panel_sidebar.add(panel_course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 60));

        panel_all_record.setBackground(new java.awt.Color(0, 102, 102));
        panel_all_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_all_record.setForeground(new java.awt.Color(255, 255, 255));
        panel_all_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_all_record.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_all_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_all_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_all_record.setText("View All Record");
        btn_all_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_all_recordMouseExited(evt);
            }
        });
        panel_all_record.add(btn_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 60));

        panel_sidebar.add(panel_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 60));

        panel_back.setBackground(new java.awt.Color(0, 102, 102));
        panel_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_back.setForeground(new java.awt.Color(255, 255, 255));
        panel_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back-button.png"))); // NOI18N
        btn_back.setText("   Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        panel_back.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 60));

        panel_sidebar.add(panel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 200, 60));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panel_sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 942, -1));

        btn_logout.setBackground(new java.awt.Color(0, 102, 102));
        btn_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_logout3.setBackground(new java.awt.Color(0, 102, 102));
        panel_logout3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_logout3.setForeground(new java.awt.Color(255, 255, 255));
        panel_logout3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_logout2.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_logout2.setText("Logout");
        btn_logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logout2MouseExited(evt);
            }
        });
        panel_logout3.add(btn_logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        btn_logout.add(panel_logout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 200, 60));

        panel_logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panel_logout.setForeground(new java.awt.Color(255, 255, 255));
        panel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        panel_logout.setText("Logout");
        panel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_logoutMouseExited(evt);
            }
        });
        btn_logout.add(panel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 60));

        panel_sidebar.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 200, 60));

        btn_edit.setBackground(new java.awt.Color(0, 102, 102));
        btn_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_logout1.setBackground(new java.awt.Color(0, 102, 102));
        panel_logout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_logout1.setForeground(new java.awt.Color(255, 255, 255));
        panel_logout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_logout1.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_logout1.setText("Logout");
        btn_logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logout1MouseExited(evt);
            }
        });
        panel_logout1.add(btn_logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        btn_edit.add(panel_logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 200, 60));

        panel_edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panel_edit.setForeground(new java.awt.Color(255, 255, 255));
        panel_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        panel_edit.setText("Edit");
        panel_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_editMouseExited(evt);
            }
        });
        btn_edit.add(panel_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 60));

        panel_sidebar.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 200, 60));

        btn_print.setBackground(new java.awt.Color(0, 102, 102));
        btn_print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        btn_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_logout5.setBackground(new java.awt.Color(0, 102, 102));
        panel_logout5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_logout5.setForeground(new java.awt.Color(255, 255, 255));
        panel_logout5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_logout4.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btn_logout4.setText("Logout");
        btn_logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logout4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logout4MouseExited(evt);
            }
        });
        panel_logout5.add(btn_logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        btn_print.add(panel_logout5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 200, 60));

        panel_print.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panel_print.setForeground(new java.awt.Color(255, 255, 255));
        panel_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        panel_print.setText("Print");
        panel_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_printMouseExited(evt);
            }
        });
        btn_print.add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 60));

        panel_sidebar.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 200, 60));

        getContentPane().add(panel_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 710));

        panel_parent.setBackground(new java.awt.Color(255, 255, 255));
        panel_parent.setForeground(new java.awt.Color(102, 102, 255));
        panel_parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_recipetNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_recipetNo.setForeground(new java.awt.Color(102, 102, 255));
        lbl_recipetNo.setText("Recipet no : SOC - ");
        panel_parent.add(lbl_recipetNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 160, 30));

        lbl_paymentMode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_paymentMode.setForeground(new java.awt.Color(102, 102, 255));
        lbl_paymentMode.setText("Mode of payment :");
        panel_parent.add(lbl_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, 30));

        txt_cheque_dd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cheque_dd.setForeground(new java.awt.Color(102, 102, 255));
        txt_cheque_dd.setText("Cheque & DD");
        panel_parent.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 160, 30));

        lbl_cheque_dd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(102, 102, 255));
        lbl_cheque_dd.setText("Cheque & DD :");
        panel_parent.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, 30));

        lbl_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(102, 102, 255));
        lbl_date.setText("Date :");
        panel_parent.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 110, 30));

        lbl_gstIN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_gstIN.setForeground(new java.awt.Color(102, 102, 255));
        lbl_gstIN.setText("GSTIN :");
        panel_parent.add(lbl_gstIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 100, 30));

        panel_child.setBackground(new java.awt.Color(255, 255, 255));
        panel_child.setForeground(new java.awt.Color(102, 102, 255));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("Head");

        jSeparator3.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Amount");

        jSeparator4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        lbl_totalInWords.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_totalInWords.setForeground(new java.awt.Color(102, 102, 255));
        lbl_totalInWords.setText("Total In words :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setText("Sr No");

        lbl_remark.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_remark.setForeground(new java.awt.Color(102, 102, 255));
        lbl_remark.setText("Remarks :");

        jSeparator5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setText("Receiver Signature");

        lbl_cgst.setBackground(new java.awt.Color(0, 153, 153));
        lbl_cgst.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cgst.setForeground(new java.awt.Color(102, 102, 255));
        lbl_cgst.setText("CGST 9% :");

        lbl_sgst.setBackground(new java.awt.Color(0, 153, 153));
        lbl_sgst.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sgst.setForeground(new java.awt.Color(102, 102, 255));
        lbl_sgst.setText("SGST 9% :");

        lbl_totalAmount.setBackground(new java.awt.Color(0, 153, 153));
        lbl_totalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_totalAmount.setForeground(new java.awt.Color(102, 102, 255));
        lbl_totalAmount.setText("Total :");

        lbl_head.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_head.setForeground(new java.awt.Color(102, 102, 255));
        lbl_head.setText("CGST 9% :");

        lbl_initialAmount.setBackground(new java.awt.Color(0, 153, 153));
        lbl_initialAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_initialAmount.setForeground(new java.awt.Color(102, 102, 255));
        lbl_initialAmount.setText("amount");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 255));
        jLabel27.setText("Total In words :");

        lbl_srNo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_srNo1.setForeground(new java.awt.Color(102, 102, 255));
        lbl_srNo1.setText("1");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 255));
        jLabel28.setText("Remarks :");

        lbl_head2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_head2.setForeground(new java.awt.Color(102, 102, 255));
        lbl_head2.setText("SGST 9%:");

        lbl_head3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_head3.setForeground(new java.awt.Color(102, 102, 255));
        lbl_head3.setText("1");

        javax.swing.GroupLayout panel_childLayout = new javax.swing.GroupLayout(panel_child);
        panel_child.setLayout(panel_childLayout);
        panel_childLayout.setHorizontalGroup(
            panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_childLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel17)
                .addGap(225, 225, 225)
                .addComponent(jLabel13)
                .addGap(339, 339, 339)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_childLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_childLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_childLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbl_srNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_childLayout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_childLayout.createSequentialGroup()
                        .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_childLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_totalInWords, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_childLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_head3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)))
                        .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_childLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_childLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_head2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(116, 116, 116)
                                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_totalAmount)
                                    .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_sgst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_cgst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_initialAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_childLayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1291, Short.MAX_VALUE))
            .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_childLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel28)
                    .addContainerGap(1146, Short.MAX_VALUE)))
        );
        panel_childLayout.setVerticalGroup(
            panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_childLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_initialAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_head, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_head3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_srNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_cgst))
                .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_childLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_sgst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_head2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_totalAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(159, 159, 159))
                    .addGroup(panel_childLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_totalInWords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_childLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
            .addGroup(panel_childLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_childLayout.createSequentialGroup()
                    .addContainerGap(223, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );

        panel_parent.add(panel_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1080, 420));

        lbl_year1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_year1.setForeground(new java.awt.Color(102, 102, 255));
        lbl_year1.setText("lbl_year1");
        panel_parent.add(lbl_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 60, 30));

        txt_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_button.setForeground(new java.awt.Color(102, 102, 255));
        txt_button.setText("Print");
        txt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buttonActionPerformed(evt);
            }
        });
        panel_parent.add(txt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 100, 30));

        lbl_rollNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_rollNo.setForeground(new java.awt.Color(102, 102, 255));
        lbl_rollNo.setText("Roll NO :  ");
        panel_parent.add(lbl_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, 31));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("RBMI");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 100, 30));

        jLabel20.setBackground(new java.awt.Color(0, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 255));
        jLabel20.setText("Rakshpal Bahadur Management Institute Bareilly");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 610, 30));

        jLabel21.setBackground(new java.awt.Color(0, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 255));
        jLabel21.setText("Faridpur Road Near ITBP Bhukara");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 390, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/resize.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 90));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 80));

        panel_parent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        panel_parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1080, 7));

        lbl_recivedForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_recivedForm.setForeground(new java.awt.Color(102, 102, 255));
        lbl_recivedForm.setText("Recived Form :");
        panel_parent.add(lbl_recivedForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Session :");
        panel_parent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 120, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("to");
        panel_parent.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, 30));

        lbl_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(102, 102, 255));
        lbl_course.setText("Course :");
        panel_parent.add(lbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("Recipet no : SOC - ");
        panel_parent.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jLabel23.setText("Mode of payment :");
        panel_parent.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, 30));

        lbl_bankName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bankName.setForeground(new java.awt.Color(102, 102, 255));
        lbl_bankName.setText("Bank No :");
        panel_parent.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 255));
        jLabel24.setText("Recived Form :");
        panel_parent.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 160, 30));

        txt_bankName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_bankName.setForeground(new java.awt.Color(102, 102, 255));
        txt_bankName.setText("Bank No :");
        panel_parent.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 160, 30));

        lbl_year2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_year2.setForeground(new java.awt.Color(102, 102, 255));
        lbl_year2.setText("lbl_year2");
        panel_parent.add(lbl_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 70, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 255));
        jLabel25.setText("Course :");
        panel_parent.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Date :");
        panel_parent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 60, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 255));
        jLabel26.setText("Roll NO :  ");
        panel_parent.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 31));

        txt_gst_no1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_gst_no1.setForeground(new java.awt.Color(102, 102, 255));
        txt_gst_no1.setText("GSTIN :");
        panel_parent.add(txt_gst_no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 70, 30));

        getContentPane().add(panel_parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1080, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseEntered
        Color clr=new Color(0,153,153);
        panel_home.setBackground(clr);
    }//GEN-LAST:event_lbl_homeMouseEntered

    private void lbl_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseExited
        Color clr=new Color(0,102,102);
        panel_home.setBackground(clr);
    }//GEN-LAST:event_lbl_homeMouseExited

    private void btn_search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseEntered
        Color clr=new Color(0,153,153);
        panel_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseEntered

    private void btn_search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseExited
        Color clr=new Color(0,102,102);
        panel_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseExited

    private void btn_edit_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseEntered
        Color clr=new Color(0,153,153);
        panel_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseEntered

    private void btn_edit_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseExited
        Color clr=new Color(0,102,102);
        panel_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseExited

    private void btn_course_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseEntered
        Color clr=new Color(0,153,153);
        panel_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseEntered

    private void btn_course_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseExited
        Color clr=new Color(0,102,102);
        panel_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseExited

    private void btn_all_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseEntered
        Color clr=new Color(0,153,153);
        panel_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_all_recordMouseEntered

    private void btn_all_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseExited
        Color clr=new Color(0,102,102);
        panel_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_all_recordMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        Color clr=new Color(0,153,153);
        panel_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        Color clr=new Color(0,102,102);
        panel_back.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseExited

    private void panel_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_editMouseEntered
        Color clr=new Color(0,153,153);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_panel_editMouseEntered

    private void panel_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_editMouseExited
        Color clr=new Color(0,102,102);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_panel_editMouseExited

    private void btn_logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout1MouseEntered

    private void btn_logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout1MouseExited

    private void btn_logout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout2MouseEntered

    private void btn_logout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout2MouseExited

    private void panel_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_logoutMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,153,153);
        btn_logout.setBackground(clr);
    }//GEN-LAST:event_panel_logoutMouseEntered

    private void panel_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_logoutMouseExited
        // TODO add your handling code here:
         Color clr=new Color(0,102,102);
        btn_logout.setBackground(clr);
    }//GEN-LAST:event_panel_logoutMouseExited

    private void btn_logout4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout4MouseEntered
        // TODO add your handling code here:
          Color clr=new Color(0,153,153);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_logout4MouseEntered

    private void btn_logout4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logout4MouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,102,102);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_logout4MouseExited

    private void panel_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_printMouseEntered
         Color clr=new Color(0,153,153);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_panel_printMouseEntered

    private void panel_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_printMouseExited
        // TODO add your handling code here:
          Color clr=new Color(0,102,102);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_panel_printMouseExited

    private void txt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buttonActionPerformed
      
    }//GEN-LAST:event_txt_buttonActionPerformed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
         Color clr=new Color(0,153,153);
        panel_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        Color clr=new Color(0,102,102);
        panel_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,153,153);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
         Color clr=new Color(0,102,102);
        panel_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void panel_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_printMouseClicked
       PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_parent.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_panel_printMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        home1 home=new home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void btn_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseClicked
          Search_Rocord search=new Search_Rocord();
        search.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_search_recordMouseClicked

    private void btn_edit_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseClicked
         Edit_Course edit=new Edit_Course();
       edit.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_edit_courseMouseClicked

    private void btn_all_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_all_recordMouseClicked
        View_All_Record record=new View_All_Record();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_all_recordMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
          home1 home=new home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void panel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_logoutMouseClicked
         int a=JOptionPane.showConfirmDialog(null,"Do you want to Logout Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_panel_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_all_record;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_course_list;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JLabel btn_edit_course;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JLabel btn_logout1;
    private javax.swing.JLabel btn_logout2;
    private javax.swing.JLabel btn_logout4;
    private javax.swing.JPanel btn_print;
    private javax.swing.JLabel btn_search_record;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cgst;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gstIN;
    private javax.swing.JLabel lbl_head;
    private javax.swing.JLabel lbl_head2;
    private javax.swing.JLabel lbl_head3;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_initialAmount;
    private javax.swing.JLabel lbl_paymentMode;
    private javax.swing.JLabel lbl_recipetNo;
    private javax.swing.JLabel lbl_recivedForm;
    private javax.swing.JLabel lbl_remark;
    private javax.swing.JLabel lbl_rollNo;
    private javax.swing.JLabel lbl_sgst;
    private javax.swing.JLabel lbl_srNo1;
    private javax.swing.JLabel lbl_totalAmount;
    private javax.swing.JLabel lbl_totalInWords;
    private javax.swing.JLabel lbl_year1;
    private javax.swing.JLabel lbl_year2;
    private javax.swing.JPanel panel_all_record;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_child;
    private javax.swing.JPanel panel_course_list;
    private javax.swing.JLabel panel_edit;
    private javax.swing.JPanel panel_edit_course;
    private javax.swing.JPanel panel_home;
    private javax.swing.JLabel panel_logout;
    private javax.swing.JPanel panel_logout1;
    private javax.swing.JPanel panel_logout3;
    private javax.swing.JPanel panel_logout5;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JLabel panel_print;
    private javax.swing.JPanel panel_search_record;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JButton txt_button;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_gst_no1;
    // End of variables declaration//GEN-END:variables
}
